# No more preloads!

wallpaper {
    monitor = HDMI-A-1
    path = /home/kami/.backgrounds/hypr/1.jpg
    # optional: fit_mode = cover # (contain/tile/fill)
}

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/2.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/3.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/4.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/5.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/6.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/7.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/8.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/9.jpg
# }

# wallpaper {
#     monitor = HDMI-A-1
#     path = /home/kami/.backgrounds/hypr/10.jpg
# }

splash = false
ipc = on
